# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-26 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='obtainedMarks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
